baseURL = "https://hexn.live/"
theme = "risotto"
title = "hex"
author = "Hector Brown"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
disableKinds = ["taxonomy", "term"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

enableRobotsTXT = true

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"

# Sidebar: about/bio
[params.about]
title = "Hector Brown"
description = "Hi. I was a Physics student in London, now unemployed and travelling around Australia. I'm interested in Unix/Linux, terminal-centric workflows, vim and FOSS in general. Mainly, I write in Python, but I'm interested in Rust, functional languages like Haskell, and shellscript. Take a look at my Github, or email me if you want to get in contact:"
#logo = "favicon.ico"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/hectorBrown/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:hectorjbrown@protonmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-stack-overflow"
title = "Stack Overflow"
url = "https://stackoverflow.com/users/2984708/hex"

#[[params.socialLinks]]
#icon = "fa-brands fa-paypal"
#title = "PayPal"
#url = "https://paypal.me/hexne"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/hector-brown-25a907252/"

[[params.socialLinks]]
icon = "fa-solid fa-key"
title = "PGP Key"
url = "/pgp.txt"

[markup.highlight]
noClasses = false

[menu]

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "phys"
name = "Phys"
url = "/phys/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.x]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true

[pagination]
pagerSize = 3
